title: Jekyll Gitbook
longtitle: Jekyll Gitbook
email: albin.touma@gmail.com

remote_theme: sighingnow/jekyll-gitbook
toc:
  enabled: true
  h-min: 1
  h_max: 3

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true

include:
  - CONTRIBUTING.md
  - index.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
